### ISSUE TITLE
LokIM roadmap plan - anonymity

### ISSUE THREAD

**Issue by michaelKurowski** [michaelKurowski/lokim2#118]
As LokIM maturity is getting closer, and closer - we should discuss an important topic which was quite important during laying first plans. Should LokIM be ultra secure, anonymous IM, or comfortable IM with useful features? There's several things to discuss.
 - Messages
   - [ ] Stored In DB
   - [ ] Stored on Client
   - [ ] Not stored at all
 - eMail Addresses of users
   - [ ] Stored as hashes
   - [ ] Stored in DB in plaintext
 - Usernames
   - [ ] One time hashes
   - [ ] One time hashes, user can set a new nickname with every login
   - [ ] Plaintext hashes stored in DB
 - IP Addresses
   - Are we able to not store them?

**Comment by michaelKurowski** [comment]
Already discussed
